### ISSUE TITLE
Java Exception Error

### ISSUE THREAD

**Issue by Armin268** [MPh-py/MPh#107]
During running the codes, I got this error.
any help would be appreciated.

ERROR:

Traceback (most recent call last):
  File "SourceFile", line 169, in com.comsol.model.util.ModelUtil.load
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "C:\Users\armin\Documents\PFC-CFD\PFC_COMSOL\MPh-Test\MPh-main\tests\capacitor.py", line 3, in <module>
    model = client.load('capacitor.mph')
  File "C:\Users\armin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mph\client.py", line 322, in load
    model = Model(self.java.load(tag, str(file)))
java.lang.java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: 'void com.comsol.nativejni.util.FlLicense.initWS0(com.comsol.nativejni.CPointer, java.lang.String)'

**Comment by john-hen** [comment]
This has been reported before. Please refer to the original issue #57 or the other duplicate #87.
