### ISSUE TITLE
calling mph.start() exits python without printing Errors

### ISSUE THREAD

**Issue by Alexander-Hoppe** [MPh-py/MPh#157]
## Setup

Windows 10 10.0.19045 Build 19045

`conda create -n mphtest`

`conda activate mphtest`

`pip install MPh`

### Running without installed COMSOL

`(mphtest) D:\\mydir\\> python`

`>>> import mph`

`>>> mph.start()`

Results in `RuntimeError: Could not locate any Comsol installation`

### Running with fresh Comsol 6.0 installation

Fresh install of COMSOL 6.0

`(mphtest) D:\\mydir\\> python`

`>>> import mph`

`>>> mph.start()`

*Windows hourglass symbol next to pointer shows up after 1 to 2 seconds, then python has exited without error and I am back in the shell*

`(mphtest) D:\\mydir\\>`

### Question

COMSOL GUI runs fine.

How can I debug this?

**Comment by john-hen** [comment]
> How can I debug this?

You can run the test suite with logging enabled: `python tools\test.py --log`. See the ReadMe's in the `tools` and `tests` folders for more details.

**Comment by Alexander-Hoppe** [comment]
Thanks for this and for this great software in general. Due to time constraints, I ended up running it on a different client (where it works). I am sorry to not have been able to get to the root of this. But I am sure that your debugging instructions will help someone else in the future.

**Comment by john-hen** [comment]
Seems like it. And apparently it crashes out of the Python session completely.

You should be able to reproduce the crash in an interactive Python prompt. I just get the Python prompt back when I do this:
```
>>> import jpype
>>> jpype.startJVM('C:\\Program Files\\COMSOL\\COMSOL60\\Multiphysics\\java\\win64\\jre\\bin\\server\\jvm.dll')
>>>
```

But then it's just JPype, not MPh, and there's nothing I can do about it. Don't see what the Windows update would have to do with it. If anything, this is a conflict with DLLs on your system that Java is trying to load (and failing). Along the lines of #49, though not exactly that as it's been fixed.

**Comment by Alexander-Hoppe** [comment]
Running these commands in the interactive prompt shows me the same behavior as for you. I am still in the interactive prompt after execution of `jpype.startJVM` and it does not crash in this case.

```
(mph) PS C:\Users\ga38haq> python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.startJVM('C:\\Program Files\\COMSOL\\COMSOL60\\Multiphysics\\java\\win64\\jre\\bin\\server\\jvm.dll')
>>>
```

Out of curiosity, when I then try to start mph, the following happens:

```
>>> import mph
>>> mph.start()
Only one client can be instantiated at a time.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ga38haq\AppData\Local\miniconda3\envs\mph\Lib\site-packages\mph\session.py", line 101, in start
    client = Client(cores=cores, version=version)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ga38haq\AppData\Local\miniconda3\envs\mph\Lib\site-packages\mph\client.py", line 151, in __init__
    raise NotImplementedError(error)
NotImplementedError: Only one client can be instantiated at a time.
>>>
```

**Comment by john-hen** [comment]
That makes sense if you were still in the same Python session. Were you?

JPype seemed to crash in your test because you'd otherwise expect the log to continue like so:
```
...
[00:00.856] Assigned name "6.0" to this installation.
[00:00.856] Starting external server process.
[00:00.856] Server restricted to 1 processor core.
[00:08.380] Server listening on port 65390.
[00:08.380] JPype version is 1.4.1.
[00:08.380] Starting Java virtual machine.
[00:08.380] JVM arguments: ['C:\\Program Files\\COMSOL\\COMSOL60\\Multiphysics\\java\\win64\\jre\\bin\\server\\jvm.dll']
[00:xx.xxx] Java virtual machine has started.
[00:xx.xxx] Connecting to server "localhost" at port 65390.
[00:xx.xxx] Disconnecting from server.
[00:xx.xxx] Exiting the Java virtual machine.
Passed in xx s.
```

I don't see why it doesn't crash when you do that manually. Maybe try also loading the Comsol Java classes. Something like:
```python
import jpype
jpype.startJVM(
    'C:/Program Files/COMSOL/COMSOL60/Multiphysics/java/win64/jre/bin/server/jvm.dll',
    classpath='C:/Program Files/COMSOL/COMSOL60/Multiphysics/apiplugins/*'
)
print('Success.')
```
I say "something like" because I have Comsol installed in a different location, so edited in the path you have it at.

The above is the only code that MPh runs between the last log message you saw in your test run and the next log message which it never got to:
https://github.com/MPh-py/MPh/blob/e24c9cccd45af9f26081ae7f1204df0830814157/mph/client.py#L181-L186

**Comment by Alexander-Hoppe** [comment]
> That makes sense if you were still in the same Python session. Were you?

Yes, it was the same Python session.



> Maybe try also loading the Comsol Java classes. Something like:
> 
> ```python
> import jpype
> jpype.startJVM(
>     'C:/Program Files/COMSOL/COMSOL60/Multiphysics/java/win64/jre/bin/server/jvm.dll',
>     classpath='C:/Program Files/COMSOL/COMSOL60/Multiphysics/apiplugins/*'
> )
> ```

Running 

```
(mph) PS C:\Users\ga38haq> python
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.startJVM(
...     'C:/Program Files/COMSOL/COMSOL60/Multiphysics/java/win64/jre/bin/server/jvm.dll',
...     classpath='C:/Program Files/COMSOL/COMSOL60/Multiphysics/apiplugins/*'
... )
(mph) PS C:\Users\ga38haq>
```

exits without error and throws me back into my shell. The `classpath` argument seems to have made the difference. My `apiplugins` folder contains some `com.comsol.*.jar` and `org.eclipse.*` files.

**Comment by john-hen** [comment]
Well, I see no reason why this happens and have no idea how to fix that. It's almost certainly a bug in JPype, rather than Java, but would be difficult to debug, even if reproducible, and if there was someone with the technical expertise (which I don't have) and access to Comsol.

For what it's worth, I see "2023-11 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5032190)" in my update history. It's not the exact same update, since it's for Windows 11, but fixes the same issues. I don't have access to a Windows 10 system with Comsol installed.

I don't know why a Windows update would make Java crash when classes are loaded. Comsol's Java classes do have external dependencies, i.e. dynamically linked system libraries, but problems there usually lead to a `java.lang.UnsatisfiedLinkError` exception, not a crash of the Java virtual machine.

I'll leave this issue open, since it's unresolved, and so people can comment here if they have something relevant to add.

**Comment by Thrameos** [comment]
I encountered a crash in dynamic loader over a missing dependency (in that case ggogle protobuf missing).   I am not sure why a missing dependency is causing a crash where it was causing a proper exception previously.  My assumption is there has been a change of behavious in the JVM which is now yielding an exception at an unexpected point leading to the failure.  Fixing the dependency problem solved the issue, but I have not had time to find the crash source.

**Comment by grauchs** [comment]
This or a similar issue, i.e. mph.start(), or in fact JVMstart(), crashing python in windows, has been fixed in jpype, see
https://github.com/jpype-project/jpype/issues/1242
