### ISSUE TITLE
No preference with name `tempfiles.saving.warnifoverwriteolder`

### ISSUE THREAD

**Issue by p-nieke** [MPh-py/MPh#50]
Hi,

First of all, thanks for sharing the great project MPh! I am looking forward to using it.
 
Today I tried to set it up on my system (Win 10 Enterprise, 64-bit). 
The installation via pip worked but I encountered some problems when using mph.start() as described in the tutorial.
 
Please find the log below - do you have an idea how to fix this issue?
 
This would be much appreciated, thank you.
 
Kind regards,
 
Philipp
 
--- 
 ```
In [2]: import mph
 
In [3]: client = mph.start(cores=1)
Traceback (most recent call last):
File "SourceFile", line 396, in com.comsol.model.util.ModelUtil.setPreference
File "SourceFile", line 619, in com.comsol.model.util.ServerModelUtil.setPreference
File "AccessController.java", line -2, in java.security.AccessController.doPrivileged 
File "SourceFile", line 622, in com.comsol.model.util.ServerModelUtil$19.run
File "SourceFile", line 2530, in com.comsol.nativeutil.preferences.Preferences.setPreference
Exception: Java Exception
 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<ipython-input-3-9a0936dc3385>", line 1, in <module>
client = mph.start(cores=1)
File "C:\Users\p\Anaconda3\lib\site-packages\mph\session.py", line 103, in start
client = Client(cores=cores, version=version)
File "C:\Users\p\Anaconda3\lib\site-packages\mph\client.py", line 141, in __init__
java.setPreference('tempfiles.saving.warnifoverwriteolder', 'off')
com.comsol.util.exceptions.FlException: Exception:
com.comsol.util.exceptions.FlException: No preference with the name X was found#tempfiles.saving.warnifoverwriteolder
Messages:
No preference with the name X was found#tempfiles.saving.warnifoverwriteolder
```

**Comment by john-hen** [comment]
You can try and run the [`create_capacitor.py`](https://github.com/MPh-py/MPh/blob/main/demos/create_capacitor.py) script from the `demos` folder. I've obviously never tested it with Comsol 5.2a, but I don't think it uses any features introduced in later versions. So it should just produce the tutorial model as a Comsol 5.2a model file.

**Comment by p-nieke** [comment]
Ok, will do.

**Comment by p-nieke** [comment]
Running the create_capacitor.py script led to another [issue](https://github.com/MPh-py/MPh/issues/51#issue-1029768878).
