### ISSUE TITLE
create_capacitor.py in Comsol 5.2a

### ISSUE THREAD

**Issue by p-nieke** [MPh-py/MPh#51]
Hi,

running the [create_capacitor.py](https://github.com/MPh-py/MPh/blob/main/demos/create_capacitor.py) script in Comsol 5.2a led to following error related to 'com.comsol.model.impl.ModelParamImpl'. 

Do you have an idea how to fix this?

Thanks, 
Philipp

`mph.start() returning the existing client instance.
Traceback (most recent call last):

  File "..\create_capacitor.py", line 14, in <module>
    (parameters/'Parameters 1').rename('parameters')

  File "C:\Users\p\Anaconda3\lib\site-packages\mph\node.py", line 261, in rename
    java = self.java

  File "C:\Users\p\Anaconda3\lib\site-packages\mph\node.py", line 181, in java
    java = parent.java

  File "C:\Users\p\Anaconda3\lib\site-packages\mph\node.py", line 179, in java
    return eval(self.groups.get(name))

  File "<string>", line 1, in <module>

AttributeError: 'com.comsol.model.impl.ModelParamImpl' object has no attribute 'group'`

**Comment by john-hen** [comment]
The tutorial model was created in Comsol 5.5. And that script recreates it assuming you have at least that version installed. You're using an older Comsol version, 5.2a. Like I said in the linked issue, running the script *may* still work if it doesn't use any of the newer features (that is, API methods). Though apparently it does. Parameter groups were introduced with Comsol 5.4. From the [release notes](https://www.comsol.com/documentation/5.4/COMSOL_ReleaseNotes):
> It is now possible to add multiple **Parameters** nodes for grouping parameters for different purposes.

That line in the Python script is however not particularly important. In fact, it's not important at all. All it does is rename the default parameter group from "Parameters 1" to just "parameters". So you can safely skip that line in the script (comment it out).
