### ISSUE TITLE
Error initialising new model with Comsol 6.0 

### ISSUE THREAD

**Issue by titian2204** [MPh-py/MPh#87]
Currently, i am trying to run MPh on windows with COMSOL.Using both v5.3a and v6.0. 
In each instance, I seem to be encountering the same java error. Testing this with 'test_standalone.py'  i get the following error:

 C:\envs\MPh\tests> python .\test_standalone.py
Traceback (most recent call last):
  File "SourceFile", line 99, in com.comsol.model.util.ModelUtil.createUnique
  File "SourceFile", line 92, in com.comsol.model.util.ModelUtil.create
  File "SourceFile", line 43, in com.comsol.model.util.ServerModelUtil.create
  File "SourceFile", line 658, in com.comsol.nativeutil.e.b.l
  File "SourceFile", line 22, in com.comsol.nativeutil.e.c.<clinit>
  File "SourceFile", line 167, in com.comsol.nativejni.util.FlLicense.getInstance
  File "SourceFile", line 72, in com.comsol.nativejni.util.FlLicense.<init>
  File "SourceFile", line -2, in com.comsol.nativejni.util.FlLicense.initWS0
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\envs\MPh\tests\test_standalone.py", line 48, in <module>
    test_start()
  File "C:\envs\MPh\tests\test_standalone.py", line 24, in test_start
    model = client.create('empty')
  File "C:\Users\IGR Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\mph\client.py", line 353, in create
    java = self.java.createUnique('model')
java.lang.java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError: 'void com.comsol.nativejni.util.FlLicense.initWS0(com.comsol.nativejni.CPointer, java.lang.String)'

If anyone can help me resolve this issue that would be great

**Comment by john-hen** [comment]
Hi, thanks for reporting this. Unfortunately, I have no idea why this happens. All I know is that I cannot reproduce the issue. A very similar, if not the same, error has been reported in #57, and there we got nowhere in terms of solving it. Though there is a work-around: to use client-server mode. Which is what MPh uses on Linux/macOS anyway, so it should be good enough. You only lose a bit of start-up performanace, which is why "stand-alone mode" is the default on Windows.
